### PR TITLE
Add sudo option for root access

### PR DESCRIPTION
**Pull request by obbiondo**
I have added a sudo option in order to give to ansible-playbook root permission. This is done to prevent some errors that may occur when performing an operation that requires root access.

### CODE REVIEW

**Comment by dawidd6** [comment]
Do you have an example operation where sudo might be needed?

**Comment by andreabiondo** [comment]
When I tried to install apt packages inside a playbook root access was needed.

**Comment by dawidd6** [comment]
You should be able to specify `sudo` in playbook itself. No need to run whole ansible as root.

**Comment by andreabiondo** [comment]
I've also tried this solution, but the problem remains. Also passing -K as option don't work.

**Comment by dawidd6** [comment]
Are you trying to run a playbook on GitHub Actions runner itself?

**Comment by andreabiondo** [comment]
Yes

**Comment by dawidd6** [comment]
Can I see the playbook and workflow?

**Comment by m-roberts** [comment]
@dawidd6 - chroot connection requires `sudo`:
```
         if os.geteuid() != 0:
             raise AnsibleError("chroot connection requires running as root")
```

Sadly, I need this - this is preventing me from using this Action

**Comment by dawidd6** [comment]
Done

**Pull request merged**
