### PR TITLE
Support installing requirements

### PR DESCRIPTION
**Pull request by dawidd6**
Closes: https://github.com/dawidd6/action-ansible-playbook/issues/12

### CODE REVIEW

**Comment by dawidd6** [comment]
@fooock does that solve your issue?

**Comment by fooock** [comment]
Hi @dawidd6 seems that role installation is working correctly but if the `requirements.yml` also contains collections it fails. My requirements file looks like this:

```yaml
---
collections:
  - name: devsec.hardening
    version: 7.0.0
roles:
  - src: nginxinc.nginx
    version: 0.18.1

  - src: nginxinc.nginx_config
    version: 0.3.0
```

The result of the action execution is this:

```
Run dawidd6/action-ansible-playbook@requirements
/usr/bin/ansible-galaxy install -r requirements.yml
- downloading role 'nginx', owned by nginxinc
- downloading role from https://github.com/nginxinc/ansible-role-nginx/archive/0.18.1.tar.gz
- extracting nginxinc.nginx to /home/runner/.ansible/roles/nginxinc.nginx
- nginxinc.nginx (0.18.1) was installed successfully
- downloading role 'nginx_config', owned by nginxinc
- downloading role from https://github.com/nginxinc/ansible-role-nginx-config/archive/0.3.0.tar.gz
- extracting nginxinc.nginx_config to /home/runner/.ansible/roles/nginxinc.nginx_config
- nginxinc.nginx_config (0.3.0) was installed successfully
/usr/bin/ansible-playbook base-playbook.yml --syntax-check --inventory-file .ansible_inventory
ERROR! the role 'devsec.hardening.os_hardening' was not found in /home/runner/work/jenkins-auto/jenkins-auto/ansible/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/runner/work/jenkins-auto/jenkins-auto/ansible

The error appears to be in '/home/runner/work/jenkins-auto/jenkins-auto/ansible/base-playbook.yml': line 22, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      import_role:
        name: devsec.hardening.os_hardening
              ^ here
Error: The process '/usr/bin/ansible-playbook' failed with exit code 1
```

I think that this change will work:

```javascript
await exec.exec("ansible-galaxy", ["role", "install", "-r", requirements])
await exec.exec("ansible-galaxy", ["collection", "install", "-r", requirements])
```

Maybe this issue can be solved by updating the Ansible version to v2.10.

**Comment by dawidd6** [comment]
```
/usr/bin/ansible-galaxy role install -r requirements.yml
- extracting nginx_role to /home/runner/.ansible/roles/nginx_role
- nginx_role (master) was installed successfully
/usr/bin/ansible-galaxy collection install -r requirements.yml
ERROR! Expecting requirements file to be a dict with the key 'collections' that contains a list of collections to install
Error: The process '/usr/bin/ansible-galaxy' failed with exit code 1
```

I don't really have any experience with requirements in Ansible. Need more help with that. Maybe a separate `collections` and `roles` inputs?

**Comment by dawidd6** [comment]
@fooock made some changes, I'm now parsing the requirements YAML file to decide which commands to run. Please test it.

**Comment by fooock** [comment]
thanks for the effort @dawidd6 it is working now!

**Pull request merged**
